### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by cooper1x** [1eeing/get_picture#1]
每次压缩都需要输入一次key，很麻烦。建议KEY可以保存到本地
而且命令最好是直接gp start开始吧，现在gp s是搜索，不知道是什么鬼。
另外希望保留input目录，也就是images，输出的文件到output，这样合理一些。可以对比源目录和转换后的目录的文件数量。

**Comment by 1eeing** [comment]
好的，谢谢提建议
有别的问题也欢迎来提~

**Comment by 1eeing** [comment]
你好，gp s是工具自带的一个爬取图片的功能，这部分内容暂且不考虑更换了。
至于
1、保存key到本地
2、保留原始目录，将图片输出到目标目录
已经在1.3.1版本更新

**Comment by 1eeing** [comment]
你好，gp s是工具自带的一个爬取图片的功能，这部分内容暂且不考虑更换了。
至于
1、保存key到本地
2、保留原始目录，将图片输出到目标目录
已经在1.3.1版本更新
