### ISSUE TITLE
无限卡在认证这里

### ISSUE THREAD

**Issue by cooper1x** [1eeing/get_picture#3]
![image](https://user-images.githubusercontent.com/9080789/72249777-0bf51880-3635-11ea-91c5-55d2072bf44d.png)
之前认证过了，也成功了，就是不压缩。
命令是gp p -p

**Comment by 1eeing** [comment]
> ![image](https://user-images.githubusercontent.com/9080789/72249777-0bf51880-3635-11ea-91c5-55d2072bf44d.png)
> 之前认证过了，也成功了，就是不压缩。
> 命令是gp p -p

去掉-p试试。-p是自定义压缩路径

**Comment by cooper1x** [comment]
@1eeing 还是一样的
![image](https://user-images.githubusercontent.com/9080789/72258957-51701080-364a-11ea-9b81-1bc0006fc529.png)

**Comment by 1eeing** [comment]
> @1eeing 还是一样的
> ![image](https://user-images.githubusercontent.com/9080789/72258957-51701080-364a-11ea-9b81-1bc0006fc529.png)

输入命令行的时候，只会压缩images文件夹下的图片

**Comment by 1eeing** [comment]
> @1eeing 还是一样的
> ![image](https://user-images.githubusercontent.com/9080789/72258957-51701080-364a-11ea-9b81-1bc0006fc529.png)

输入命令行的时候，只会压缩当前路径下，images文件夹下的图片

**Comment by kaicheng-huang** [comment]
![微信图片_20200908104355](https://user-images.githubusercontent.com/25633475/92427911-4b720580-f1c0-11ea-97be-27fccf5f380b.png)
为何一直报401

**Comment by 1eeing** [comment]
> ![微信图片_20200908104355](https://user-images.githubusercontent.com/25633475/92427911-4b720580-f1c0-11ea-97be-27fccf5f380b.png)
> 为何一直报401

具体可以查看tinypng api对于该错误的描述
https://tinypng.com/developers/reference/nodejs#error-handling
